#data_path: "datasets/diffinfinite_patches_v0_o6-4.5/"
data_path: "datasets/ILSVRC2012_img_val/"
checkpoint_path: "checkpoints/"

using_extractor: "dino" #  Which feature extractor [simclr_v2, dino, plip, None] 
using_version: "vit_small" # If dino [vit_small, vit_base]
using_aggregator: "mlknn"

extractors:
  simclr_v2:
      versions:
        r50_1x_sk0:
          dimensionality: 100
        r101_1x_sk0: 
          dimensionality: 100
  dino:
      versions:
        resnet50: 
          dimensionality: 2048
        vit_base: 
          dimensionality: 768
          avgpool_patchtokens: True
          n_last_blocks: 1
        vit_small: 
          dimensionality: 384

