checkpoint_path: "checkpoints/"

using_extractor: "simclr_v2"

extractors:
  simclr_v2:        #  Which feature extractor [simclr_v2] 
      versions:
        r50_1x_sk0: 100
        r101_1x_sk0: 100

